variables:
    BRANCH: dev
    TAG: $CI_COMMIT_TAG
    VER: alpha
    SONAR_TOKEN: $SONAR_TOKEN
    
stages:          
    - sast
    - build
    - deploy
    - dast

sonarqube-test:
    tags:
        - shared
    stage: sast 
    only:
        - tags
        - branches
    script:
        - echo $SONAR_TOKEN
        - /opt/sonar-scanner/bin/sonar-scanner -Dsonar.host.url=http://10.8.60.44:9000/ -Dsonar.branch.name=$BRANCH -Dsonar.projectName=Mongection-TSEL -Dsonar.projectKey=mongection-tsel -Dsonar.token=${SONAR_TOKEN} -Dsonar.sources=. -Dsonar.qualitygate.wait=true
    allow_failure: true
    
build-image-and-push-to-dockerhub:
    tags:
        - shared
    stage: build
    only:
        - tags
    when: manual
    script:
        - docker build . -t docker.io/prospica/mongection:$TAG -f deployments/mongection.Dockerfile
        - docker build . -t docker.io/prospica/monggo-db:$TAG -f deployments/mongo.Dockerfile
        - docker login --username=${DOCKER_USR} --password=${DOCKER_PSW} docker.io
        - docker push docker.io/prospica/mongection:$TAG
        - docker push docker.io/prospica/monggo-db:$TAG

deploy-to-ocp:
    tags:
        - shared
    stage: deploy
    only:
        - tags
    when: manual
    script:
        - sed -i "s/$VER-.*/$TAG'/" deployment-app.yaml
        - sed -i "s/$VER-.*/$TAG'/" deployment-db.yaml
        - oc login --token ${OCP_TOKEN} --server=https://api.dev.awankinton.my.id:6443 --insecure-skip-tls-verify
        - oc apply -f deployment-app.yaml
        - oc apply -f deployment-db.yaml