variables:
    TAG: $CI_COMMIT_TAG
stages:          
    - security-test
    - build
    - deploy

sast:
    tags:
        - datadog
    rules:
        - if: $CI_COMMIT_TAG =~ /^ocp/i
    stage: security-test 
    before_script:
        - export DD_SITE="us5.datadoghq.com"
        - export DD_API_KEY=$DATADOG_API_KEY
        - export DD_APP_KEY=$DATADOG_APP_KEY
    script:
        - /usr/local/datadog-static-analyzer -i . -o /home/gitlab-runner/report.sarif -f sarif
        - datadog-ci sarif upload /home/gitlab-runner/report.sarif

sca:
    tags:
        - datadog
    rules:
        - if: $CI_COMMIT_TAG =~ /^ocp/i
    stage: security-test 
    before_script:
        - export DD_SITE="us5.datadoghq.com"
        - export DD_API_KEY=$DATADOG_API_KEY
        - export DD_APP_KEY=$DATADOG_APP_KEY
    script:
        - /osv-scanner/osv-scanner --skip-git -r --experimental-only-packages --format=cyclonedx-1-5 --paths-relative-to-scan-dir  --output=/home/gitlab-runner/sbom.json .
        - datadog-ci sbom upload /home/gitlab-runner/sbom.json

quality-gate:
    tags:
        - datadog
    rules:
        - if: $CI_COMMIT_TAG =~ /^ocp/i
    stage: security-test
    needs: ["sast", "sca"]
    before_script:
        - export DD_SITE="us5.datadoghq.com"
        - export DD_API_KEY=$DATADOG_API_KEY
        - export DD_APP_KEY=$DATADOG_APP_KEY
    script:
        - datadog-ci gate evaluate
        
build-and-push-image:
    tags:
        - datadog
    stage: build
    only:
        - tags
    script:
        - docker build . -t registry.i-3.my.id:5500/mongection/app:$TAG -f deployments/mongection.Dockerfile
        - docker build . -t registry.i-3.my.id:5500/mongection/db-mongo:$TAG -f deployments/mongo.Dockerfile
        - docker login --username=$NEXUS_USR --password=$NEXUS_PSW registry.i-3.my.id:5500
        - docker push registry.i-3.my.id:5500/mongection/app:$TAG
        - docker push registry.i-3.my.id:5500/mongection/db-mongo:$TAG

deploy-to-ocp:
    tags:
        - shared
    stage: deploy
    only:
        - tags
    before_script:
        - export VER=$(echo $CI_COMMIT_TAG | grep -P '^[^-]*' -o)
    script:
        - sed -i "s/ocp-.*/$TAG'/" deployment-app.yaml
        - sed -i "s/ocp-.*/$TAG'/" deployment-db.yaml
        # - sed -i "s/$VER-.*/$TAG'/" deployment-app.yaml
        # - sed -i "s/$VER-.*/$TAG'/" deployment-db.yaml
        - oc login --token $OCP_TOKEN --server=https://api.lab.i-3.my.id:6443 --insecure-skip-tls-verify
        - oc apply -f deployment-app.yaml
        - oc apply -f deployment-db.yaml
