variables:
    BRANCH: dev
    TAG: $CI_COMMIT_TAG
stages:          
    - sast
    - build
    - deploy
    - dast

sonarqube-test:
    tags:
        - shared
    stage: sast 
    only:
        - tags
    script:
        - echo $TAG
        - sonar-scanner -Dsonar.host.url=http://10.8.60.44:9000/ -Dsonar.branch.name=$BRANCH -Dsonar.projectName=Mongection-TSEL -Dsonar.projectKey=mongection-tsel -Dsonar.token=$SONAR_TOKEN -Dsonar.sources=. -Dsonar.qualitygate.wait=true

# build:
#     stage: build
#     only:
#         - tags
#     when: manual
#     script:
#         - docker build . -t docker.io/prospica/mongection:$TAG -f deployments/mongection.Dockerfile
#         - docker build . -t docker.io/prospica/monggo-db:$TAG -f deployments/mongo.Dockerfile
#         - docker login --username=$dockerCreds_USR --password=$dockerCreds_PSW docker.io
#         - docker push docker.io/prospica/mongection:$TAG
#         - docker push docker.io/prospica/monggo-db:$TAG
   
  




